name: Detekt

on:
  workflow_call:

jobs:
  detekt:
    name: Detekt Debug Variant
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew detektAll

